Implemented Arcade Drive
Team293/InfiniteRecharge pull request #13
Opened 2021-02-18 14:21 UTC by NotVinnny

### Purpose
Robot movement can be controlled with Xbox controller

### Description
Implemented basic arcade drive in arcade drive command and is called in drivetrain subsystem

### Testing
Code builds but is not tested

2021-02-18 14:24 UTC, cartha353 commented
Do we want to pull into master even without any robot testing

2021-02-18 14:55 UTC, bjmcternan commented
No, code that has not been tested can _never_ be brought into master. You've broken the build if that happens

2021-02-18 15:15 UTC, bjmcternan requested changes
Looks good. Some whitespace issues. Let's change the X and Y variable names in arcade drive. It's even more important that we test this before we merge it since this is a major conversion

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ArcadeDrive.java
> +        m_drivetrain.arcadeDrive(m_xboxcontroller.getY(Hand.kLeft), m_xboxcontroller.getX(Hand.kLeft));
This is good. This is where would would bring in the use of the triggers or the right thumbstick for control

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ExtendClimber.java
> +
Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ExtendClimber.java
> +
Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/ExtendClimber.java
> +
2 Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/LocateTarget.java
> +        addRequirements(m_targeting); // Is this needed?
@BobTheLegend Do you know if LocatTarget requires the targeting subsystem? This might cause other things not to work

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/LocateTarget.java
> +		//Get velocity data from targeting
Extra tab

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/commands/SmartLauncher.java
> +    	//Get target RPM
Tab issue

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
Extra whitespace

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
Extra 2 whitespaces

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        m_drivetrain.arcadeDrive(y, x);
Nice! This is what I was thinking to do. Let's rename Y and X to better variables though. By themselves, Y and X don't have much meaning

2021-02-18 15:15 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Feeder.java
> +	private CANSparkMax feederMotor;
Tab issue

2021-03-01 14:12 UTC, bjmcternan requested changes

2021-03-01 14:12 UTC, bjmcternan commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        rightTalonLead.config_kF(0,KF,10);
Please use the constants to replace the 0 (PID index) and 10 (timeout)

2021-03-02 22:25 UTC, bjmcternan approved these changes
There's some minor changes we can make but we'll get them in the next ticket. Nice work

2021-03-04 21:33 UTC, merged